authorName: default
experimentName: mnist
trialConcurrency: 1
maxExecDuration: 2h
maxTrialNum: 150
trainingServicePlatform: local
useAnnotation: false
searchSpacePath: search_space.json
tuner:
  builtinTunerName: TPE # TPE, Random, Anneal, Evolution, SMAC, BatchTuner, NetworkMorphism, MetisTuner, GPTuner, RL
  classArgs:
    optimize_mode: maximize
trial:
  command: python3 main_b.py
  codeDir: .